export const Desa: any[] = [
	{ id: 201, nama: 'Ambokembang', kec: 'Kedungwuni'},
	{ id: 262, nama: 'Api-Api', kec: 'Wonokerto'},
	{ id: 165, nama: 'Babalan Kidul', kec: 'Bojong'},
	{ id: 166, nama: 'Babalanlor', kec: 'Bojong'},
	{ id: 74, nama: 'Banjarejo', kec: 'Karanganyar'},
	{ id: 50, nama: 'Banjarsari', kec: 'Talun'},
	{ id: 30, nama: 'Bantar Kulon', kec: 'Lebakbarang'},
	{ id: 51, nama: 'Batursari', kec: 'Talun'},
	{ id: 263, nama: 'Bebel', kec: 'Wonokerto'},
	{ id: 15, nama: 'Bedagung', kec: 'Paninggaran'},
	{ id: 152, nama: 'Blacanan', kec: 'Siwalan'},
	{ id: 60, nama: 'Bligorejo', kec: 'Doro'},
	{ id: 153, nama: 'Blimbing Wuluh', kec: 'Siwalan'},
	{ id: 1, nama: 'Bodas', kec: 'Kandangserang'},
	{ id: 167, nama: 'Bojong Minggir', kec: 'Bojong'},
	{ id: 168, nama: 'Bojong Wetan', kec: 'Bojong'},
	{ id: 2, nama: 'Bojongkoneng', kec: 'Kandangserang'},
	{ id: 169, nama: 'Bojonglor', kec: 'Bojong'},
	{ id: 251, nama: 'Bondansari', kec: 'Wiradesa'},
	{ id: 16, nama: 'Botosari', kec: 'Paninggaran'},
	{ id: 154, nama: 'Boyo Teluk', kec: 'Siwalan'},
	{ id: 89, nama: 'Brengkolang', kec: 'Kajen'},
	{ id: 113, nama: 'Brondong', kec: 'Kesesi'},
	{ id: 3, nama: 'Bubak', kec: 'Kandangserang'},
	{ id: 202, nama: 'Bugangan', kec: 'Kedungwuni'},
	{ id: 170, nama: 'Bukur', kec: 'Bojong'},
	{ id: 136, nama: 'Bulak Pelem', kec: 'Sragi'},
	{ id: 137, nama: 'Bulaksari', kec: 'Sragi'},
	{ id: 228, nama: 'Coprayan', kec: 'Buaran'},
	{ id: 235, nama: 'Curug', kec: 'Tirto'},
	{ id: 41, nama: 'Curugmuncar', kec: 'Petungkriyono'},
	{ id: 236, nama: 'Dadirejo', kec: 'Tirto'},
	{ id: 252, nama: 'Delegtukang', kec: 'Wiradesa'},
	{ id: 31, nama: 'Depok', kec: 'Lebakbarang'},
	{ id: 155, nama: 'Depok', kec: 'Siwalan'},
	{ id: 17, nama: 'Domiyang', kec: 'Paninggaran'},
	{ id: 52, nama: 'Donowangun', kec: 'Talun'},
	{ id: 61, nama: 'Doro', kec: 'Doro'},
	{ id: 62, nama: 'Dororejo', kec: 'Doro'},
	{ id: 171, nama: 'Duwet', kec: 'Bojong'},
	{ id: 187, nama: 'Galang Pengampon Gede', kec: 'Wonopringgo'},
	{ id: 90, nama: 'Gandarum', kec: 'Kajen'},
	{ id: 4, nama: 'Garungwiyoro', kec: 'Kandangserang'},
	{ id: 138, nama: 'Gebangkerep', kec: 'Sragi'},
	{ id: 91, nama: 'Gejlig', kec: 'Kajen'},
	{ id: 5, nama: 'Gembong', kec: 'Kandangserang'},
	{ id: 188, nama: 'Getas', kec: 'Wonopringgo'},
	{ id: 189, nama: 'Gondang', kec: 'Wonopringgo'},
	{ id: 42, nama: 'Gumelem', kec: 'Petungkriyono'},
	{ id: 75, nama: 'Gutomo', kec: 'Karanganyar'},
	{ id: 63, nama: 'Harjosari', kec: 'Doro'},
	{ id: 114, nama: 'Jagung', kec: 'Kesesi'},
	{ id: 172, nama: 'Jajar Wayang', kec: 'Bojong'},
	{ id: 237, nama: 'Jeruksari', kec: 'Tirto'},
	{ id: 190, nama: 'Jetak Kidul', kec: 'Wonopringgo'},
	{ id: 191, nama: 'Jetak Lengkong', kec: 'Wonopringgo'},
	{ id: 53, nama: 'Jolotigo', kec: 'Talun'},
	{ id: 217, nama: 'Jrebeng Kembang', kec: 'Karangdadap'},
	{ id: 253, nama: 'Kadipaten', kec: 'Wiradesa'},
	{ id: 115, nama: 'Kaibahan', kec: 'Kesesi'},
	{ id: 92, nama: 'Kajongan', kec: 'Kajen'},
	{ id: 18, nama: 'Kaliboja', kec: 'Paninggaran'},
	{ id: 218, nama: 'Kaligawe', kec: 'Karangdadap'},
	{ id: 139, nama: 'Kalijambe', kec: 'Sragi'},
	{ id: 93, nama: 'Kalijoyo', kec: 'Kajen'},
	{ id: 219, nama: 'Kalilembu', kec: 'Karangdadap'},
	{ id: 116, nama: 'Kalimade', kec: 'Kesesi'},
	{ id: 64, nama: 'Kalimojosari', kec: 'Doro'},
	{ id: 19, nama: 'Kaliombo', kec: 'Paninggaran'},
	{ id: 173, nama: 'Kalipancur', kec: 'Bojong'},
	{ id: 54, nama: 'Kalirejo', kec: 'Talun'},
	{ id: 254, nama: 'Kampil', kec: 'Wiradesa'},
	{ id: 6, nama: 'Kandangserang', kec: 'Kandangserang'},
	{ id: 32, nama: 'Kapundutan', kec: 'Lebakbarang'},
	{ id: 76, nama: 'Karang Gondang', kec: 'Karanganyar'},
	{ id: 238, nama: 'Karanganyar', kec: 'Tirto'},
	{ id: 55, nama: 'Karangasem', kec: 'Talun'},
	{ id: 220, nama: 'Karangdadap', kec: 'Karangdadap'},
	{ id: 203, nama: 'Karangdowo', kec: 'Kedungwuni'},
	{ id: 7, nama: 'Karanggondang', kec: 'Kandangserang'},
	{ id: 255, nama: 'Karangjati', kec: 'Wiradesa'},
	{ id: 239, nama: 'Karangjompo', kec: 'Tirto'},
	{ id: 117, nama: 'Karangrejo', kec: 'Kesesi'},
	{ id: 77, nama: 'Karangsari', kec: 'Karanganyar'},
	{ id: 174, nama: 'Karangsari', kec: 'Bojong'},
	{ id: 118, nama: 'Karyomukti', kec: 'Kesesi'},
	{ id: 43, nama: 'Kasimpar', kec: 'Petungkriyono'},
	{ id: 256, nama: 'Kauman', kec: 'Wiradesa'},
	{ id: 78, nama: 'Kayugeritan', kec: 'Karanganyar'},
	{ id: 44, nama: 'Kayupuring', kec: 'Petungkriyono'},
	{ id: 94, nama: 'Kebon Agung', kec: 'Kajen'},
	{ id: 221, nama: 'Kebonrowo Pucang', kec: 'Karangdadap'},
	{ id: 222, nama: 'Kebonsari', kec: 'Karangdadap'},
	{ id: 223, nama: 'Kedung Kebo', kec: 'Karangdadap'},
	{ id: 204, nama: 'Kedung Patangewu', kec: 'Kedungwuni'},
	{ id: 140, nama: 'Kedungjaran', kec: 'Sragi'},
	{ id: 175, nama: 'Kemasan', kec: 'Bojong'},
	{ id: 257, nama: 'Kemplong', kec: 'Wiradesa'},
	{ id: 229, nama: 'Kertijayan', kec: 'Buaran'},
	{ id: 119, nama: 'Kesesi', kec: 'Kesesi'},
	{ id: 141, nama: 'Ketanon Ageng', kec: 'Sragi'},
	{ id: 176, nama: 'Ketitang Kidul', kec: 'Bojong'},
	{ id: 177, nama: 'Ketitanglor', kec: 'Bojong'},
	{ id: 8, nama: 'Klesem', kec: 'Kandangserang'},
	{ id: 142, nama: 'Klunjukan', kec: 'Sragi'},
	{ id: 20, nama: 'Krandegan', kec: 'Paninggaran'},
	{ id: 120, nama: 'Krandon', kec: 'Kesesi'},
	{ id: 143, nama: 'Krasakageng', kec: 'Sragi'},
	{ id: 56, nama: 'Krompeng', kec: 'Talun'},
	{ id: 79, nama: 'Kulu', kec: 'Karanganyar'},
	{ id: 95, nama: 'Kutorejo', kec: 'Kajen'},
	{ id: 33, nama: 'Kutorembet', kec: 'Lebakbarang'},
	{ id: 96, nama: 'Kutorojo', kec: 'Kajen'},
	{ id: 65, nama: 'Kutosari', kec: 'Doro'},
	{ id: 80, nama: 'Kutosari', kec: 'Karanganyar'},
	{ id: 192, nama: 'Kwagean', kec: 'Wonopringgo'},
	{ id: 121, nama: 'Kwasen', kec: 'Kesesi'},
	{ id: 205, nama: 'Kwayangan', kec: 'Kedungwuni'},
	{ id: 122, nama: 'Kwigaran', kec: 'Kesesi'},
	{ id: 21, nama: 'Lambanggelun', kec: 'Paninggaran'},
	{ id: 9, nama: 'Lambur', kec: 'Kandangserang'},
	{ id: 123, nama: 'Langensari', kec: 'Kesesi'},
	{ id: 206, nama: 'Langkap', kec: 'Kedungwuni'},
	{ id: 66, nama: 'Larikan', kec: 'Doro'},
	{ id: 34, nama: 'Lebakbarang', kec: 'Lebakbarang'},
	{ id: 178, nama: 'Legok Clile', kec: 'Bojong'},
	{ id: 193, nama: 'Legok Gunung', kec: 'Wonopringgo'},
	{ id: 81, nama: 'Legok Kalong', kec: 'Karanganyar'},
	{ id: 67, nama: 'Lemah Abang', kec: 'Doro'},
	{ id: 82, nama: 'Limbangan', kec: 'Karanganyar'},
	{ id: 97, nama: 'Linggoasri', kec: 'Kajen'},
	{ id: 224, nama: 'Logandeng', kec: 'Karangdadap'},
	{ id: 83, nama: 'Lolong', kec: 'Karanganyar'},
	{ id: 22, nama: 'Lumeneng', kec: 'Paninggaran'},
	{ id: 10, nama: 'Luragung', kec: 'Kandangserang'},
	{ id: 156, nama: 'Mejasem', kec: 'Siwalan'},
	{ id: 35, nama: 'Mendolo', kec: 'Lebakbarang'},
	{ id: 179, nama: 'Menjangan', kec: 'Bojong'},
	{ id: 57, nama: 'Mesoyi', kec: 'Talun'},
	{ id: 144, nama: 'Mrican', kec: 'Sragi'},
	{ id: 124, nama: 'Mulyorejo', kec: 'Kesesi'},
	{ id: 240, nama: 'Mulyorejo', kec: 'Tirto'},
	{ id: 241, nama: 'Ngalian', kec: 'Tirto'},
	{ id: 23, nama: 'Notogiwang', kec: 'Paninggaran'},
	{ id: 98, nama: 'Nyamok', kec: 'Kajen'},
	{ id: 242, nama: 'Pacar', kec: 'Tirto'},
	{ id: 225, nama: 'Pagumengan Mas', kec: 'Karangdadap'},
	{ id: 157, nama: 'Pait', kec: 'Siwalan'},
	{ id: 207, nama: 'Pajomblangan', kec: 'Kedungwuni'},
	{ id: 208, nama: 'Pakisputih', kec: 'Kedungwuni'},
	{ id: 230, nama: 'Pakumbulan', kec: 'Buaran'},
	{ id: 36, nama: 'Pamutuh', kec: 'Lebakbarang'},
	{ id: 243, nama: 'Pandan Arum', kec: 'Tirto'},
	{ id: 226, nama: 'Pangkah', kec: 'Karangdadap'},
	{ id: 24, nama: 'Paninggaran', kec: 'Paninggaran'},
	{ id: 180, nama: 'Pantianom', kec: 'Bojong'},
	{ id: 125, nama: 'Pantirejo', kec: 'Kesesi'},
	{ id: 231, nama: 'Paweden', kec: 'Buaran'},
	{ id: 264, nama: 'Pecakaran', kec: 'Wonokerto'},
	{ id: 84, nama: 'Pedawang', kec: 'Karanganyar'},
	{ id: 194, nama: 'Pegaden Tengah', kec: 'Wonopringgo'},
	{ id: 227, nama: 'Pegandon', kec: 'Karangdadap'},
	{ id: 99, nama: 'Pekiringan Ageng', kec: 'Kajen'},
	{ id: 100, nama: 'Pekiringan Alit', kec: 'Kajen'},
	{ id: 265, nama: 'Pesanggrahan', kec: 'Wonokerto'},
	{ id: 258, nama: 'Petukangan', kec: 'Wiradesa'},
	{ id: 209, nama: 'Podo', kec: 'Kedungwuni'},
	{ id: 85, nama: 'Pododadi', kec: 'Karanganyar'},
	{ id: 126, nama: 'Podosari', kec: 'Kesesi'},
	{ id: 127, nama: 'Ponolawen', kec: 'Kesesi'},
	{ id: 101, nama: 'Pringsurat', kec: 'Kajen'},
	{ id: 210, nama: 'Proto', kec: 'Kedungwuni'},
	{ id: 244, nama: 'Pucung', kec: 'Tirto'},
	{ id: 68, nama: 'Pungangan', kec: 'Doro'},
	{ id: 145, nama: 'Purwodadi', kec: 'Sragi'},
	{ id: 146, nama: 'Purworejo', kec: 'Sragi'},
	{ id: 181, nama: 'Randu Muktiwaren', kec: 'Bojong'},
	{ id: 69, nama: 'Randusari', kec: 'Doro'},
	{ id: 182, nama: 'Rejosari', kec: 'Bojong'},
	{ id: 158, nama: 'Rembun', kec: 'Siwalan'},
	{ id: 211, nama: 'Rengas', kec: 'Kedungwuni'},
	{ id: 70, nama: 'Rogoselo', kec: 'Doro'},
	{ id: 212, nama: 'Rowocacing', kec: 'Kedungwuni'},
	{ id: 195, nama: 'Rowokembu', kec: 'Wonopringgo'},
	{ id: 102, nama: 'Rowolaku', kec: 'Kajen'},
	{ id: 266, nama: 'Rowoyoso', kec: 'Wonokerto'},
	{ id: 103, nama: 'Sabarwangi', kec: 'Kajen'},
	{ id: 213, nama: 'Salakbrojo', kec: 'Kedungwuni'},
	{ id: 104, nama: 'Salit', kec: 'Kajen'},
	{ id: 105, nama: 'Sambiroto', kec: 'Kajen'},
	{ id: 245, nama: 'Samborejo', kec: 'Tirto'},
	{ id: 196, nama: 'Sampih', kec: 'Wonopringgo'},
	{ id: 106, nama: 'Sangkan Joyo', kec: 'Kajen'},
	{ id: 197, nama: 'Sastrodirjan', kec: 'Wonopringgo'},
	{ id: 25, nama: 'Sawangan', kec: 'Paninggaran'},
	{ id: 71, nama: 'Sawangan', kec: 'Doro'},
	{ id: 183, nama: 'Sembung Jambu', kec: 'Bojong'},
	{ id: 267, nama: 'Semut', kec: 'Wonokerto'},
	{ id: 58, nama: 'Sengare', kec: 'Talun'},
	{ id: 72, nama: 'Sidoharjo', kec: 'Doro'},
	{ id: 86, nama: 'Sidomukti', kec: 'Karanganyar'},
	{ id: 37, nama: 'Sidomulyo', kec: 'Lebakbarang'},
	{ id: 128, nama: 'Sidomulyo', kec: 'Kesesi'},
	{ id: 246, nama: 'Sidorejo', kec: 'Tirto'},
	{ id: 129, nama: 'Sidosari', kec: 'Kesesi'},
	{ id: 268, nama: 'Sijambe', kec: 'Wonokerto'},
	{ id: 147, nama: 'Sijeruk', kec: 'Sragi'},
	{ id: 247, nama: 'Silirejo', kec: 'Tirto'},
	{ id: 232, nama: 'Simbang Wetan', kec: 'Buaran'},
	{ id: 45, nama: 'Simego', kec: 'Petungkriyono'},
	{ id: 107, nama: 'Sinangoh Prendeng', kec: 'Kajen'},
	{ id: 159, nama: 'Siwalan', kec: 'Siwalan'},
	{ id: 108, nama: 'Sokoyoso', kec: 'Kajen'},
	{ id: 46, nama: 'Songgodadi', kec: 'Petungkriyono'},
	{ id: 130, nama: 'Srinahan', kec: 'Kesesi'},
	{ id: 11, nama: 'Sukoharjo', kec: 'Kandangserang'},
	{ id: 131, nama: 'Sukorejo', kec: 'Kesesi'},
	{ id: 87, nama: 'Sukosari', kec: 'Karanganyar'},
	{ id: 148, nama: 'Sumub Kidul', kec: 'Sragi'},
	{ id: 149, nama: 'Sumub Lor', kec: 'Sragi'},
	{ id: 184, nama: 'Sumur Jomblangbogo', kec: 'Bojong'},
	{ id: 198, nama: 'Surabayan', kec: 'Wonopringgo'},
	{ id: 12, nama: 'Tajur', kec: 'Kandangserang'},
	{ id: 59, nama: 'Talun', kec: 'Talun'},
	{ id: 109, nama: 'Tambakroto', kec: 'Kajen'},
	{ id: 26, nama: 'Tanggeran', kec: 'Paninggaran'},
	{ id: 214, nama: 'Tangkil Kulon', kec: 'Kedungwuni'},
	{ id: 215, nama: 'Tangkil Tengah', kec: 'Kedungwuni'},
	{ id: 248, nama: 'Tanjung', kec: 'Tirto'},
	{ id: 110, nama: 'Tanjung Kulon', kec: 'Kajen'},
	{ id: 111, nama: 'Tanjungsari', kec: 'Kajen'},
	{ id: 150, nama: 'Tegal Suruh', kec: 'Sragi'},
	{ id: 249, nama: 'Tegaldowo', kec: 'Tirto'},
	{ id: 151, nama: 'Tegalontar', kec: 'Sragi'},
	{ id: 38, nama: 'Tembelang Gunung', kec: 'Lebakbarang'},
	{ id: 160, nama: 'Tengeng Wetan', kec: 'Siwalan'},
	{ id: 161, nama: 'Tengengkulon', kec: 'Siwalan'},
	{ id: 27, nama: 'Tenogo', kec: 'Paninggaran'},
	{ id: 39, nama: 'Timbangsari', kec: 'Lebakbarang'},
	{ id: 47, nama: 'Tlogohendro', kec: 'Petungkriyono'},
	{ id: 48, nama: 'Tlogopakis', kec: 'Petungkriyono'},
	{ id: 216, nama: 'Tosaran', kec: 'Kedungwuni'},
	{ id: 13, nama: 'Trajumas', kec: 'Kandangserang'},
	{ id: 269, nama: 'Tratebang', kec: 'Wonokerto'},
	{ id: 162, nama: 'Tunjungsari', kec: 'Siwalan'},
	{ id: 132, nama: 'Ujung Negoro', kec: 'Kesesi'},
	{ id: 185, nama: 'Wangandowo', kec: 'Bojong'},
	{ id: 14, nama: 'Wangkelang', kec: 'Kandangserang'},
	{ id: 259, nama: 'Warukidul', kec: 'Wiradesa'},
	{ id: 260, nama: 'Warulor', kec: 'Wiradesa'},
	{ id: 133, nama: 'Watugajah', kec: 'Kesesi'},
	{ id: 134, nama: 'Watupayung', kec: 'Kesesi'},
	{ id: 233, nama: 'Watusalam', kec: 'Buaran'},
	{ id: 28, nama: 'Werdi', kec: 'Paninggaran'},
	{ id: 270, nama: 'Werdi', kec: 'Wonokerto'},
	{ id: 29, nama: 'Winduaji', kec: 'Paninggaran'},
	{ id: 135, nama: 'Windurojo', kec: 'Kesesi'},
	{ id: 261, nama: 'Wiradesa', kec: 'Wiradesa'},
	{ id: 186, nama: 'Wiroditan', kec: 'Bojong'},
	{ id: 271, nama: 'Wonokerto Kulon', kec: 'Wonokerto'},
	{ id: 272, nama: 'Wonokerto Wetan', kec: 'Wonokerto'},
	{ id: 199, nama: 'Wonopringgo', kec: 'Wonopringgo'},
	{ id: 112, nama: 'Wonorejo', kec: 'Kajen'},
	{ id: 200, nama: 'Wonorejo', kec: 'Wonopringgo'},
	{ id: 88, nama: 'Wonosari', kec: 'Karanganyar'},
	{ id: 163, nama: 'Wonosari', kec: 'Siwalan'},
	{ id: 40, nama: 'wonosido', kec: 'Lebakbarang'},
	{ id: 234, nama: 'Wonoyoso', kec: 'Buaran'},
	{ id: 73, nama: 'Wringin Agung', kec: 'Doro'},
	{ id: 250, nama: 'Wuled', kec: 'Tirto'},
	{ id: 49, nama: 'Yosorejo', kec: 'Petungkriyono'},
	{ id: 164, nama: 'Yosorejo', kec: 'Siwalan'},
]